### ISSUE TITLE
pdfminorversion cannot be changed

### ISSUE THREAD

**Issue by jen-is-beaming** [gillescastel/university-setup#2]
In preamble.tex the \pdfminorversion=7 on line 250 appears to create an error for my machine. I get the message that "\pdfminorversion cannot be changed" after something has been written to the pdf. Moving the value assignment to an earlier line, like 11, fixes the issue.

**Comment by siemdejong** [comment]
I also experience this issue and also fixed it by moving \pdfminorversion to the start of the preamble. It must appear before any data is written to a pdf.

From the docs:
![image](https://user-images.githubusercontent.com/28396796/78828520-1e3ce380-79e5-11ea-995f-3e648be8c68b.png)

**Comment by gillescastel** [comment]
For some reason, I don't have this issue. However, feel free to add a pull request to move `\pdfminorversion` to the top.
