### ISSUE TITLE
More detailed Documentation/Comments

### ISSUE THREAD

**Issue by Zackhardtoname** [gillescastel/university-setup#3]
Is there any chance we could get more detailed documentation/comments for the scripts?
Like what functionalities each script does. That would be awesome!

**Comment by gillescastel** [comment]
Sure, that would probably be helpful. I'll write some documentation in the coming days.

**Comment by kataklasm** [comment]
After I'm done with my exams in two weeks I'll start working on adding proper documentation to all the scripts. Maybe even write a detailed guide @gillescastel could publish on his blog or as a wiki on this repo.

**Comment by gillescastel** [comment]
Added some basic documentation in the README. If there is anything specific you're stuck with or if you think something needs more clarification, feel free to reopen this issue!
