### ISSUE TITLE
TypeError in countdown.py (l.138)

### ISSUE THREAD

**Issue by kataklasm** [gillescastel/university-setup#5]
When I run `python scripts/countdown.py` everything works as expected if there is no event in the relevant calendar before the current time. Let's Say I have course1 from 10am to 11am and course2 from 12am to 1pm. If I run `python scripts/countdown.py` at 9am then everything works properly. But starting from 10am the program breaks with the following error:

```
Traceback (most recent call last):
  File "countdown.py", line 224, in <module>
    main()
  File "countdown.py", line 207, in main
    scheduler.run()
  File "/usr/lib64/python3.7/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "countdown.py", line 139, in activate_course
    None
File "countdown.py", line 138, in <genexpr>
    if course.info['title'].lower() in event['summary'].lower()),
TypeError: string indices must be integers
```
Unfortunately, I haven't found why it sees `course.info` or `event` as strings yet.

**Comment by gillescastel** [comment]
Thanks for the bug report.

Cannot reproduce with my setup. What is `course.info` when that happens? What is `event`?

**Comment by kataklasm** [comment]
I'm embarrassed... I had another look and found that my info.yaml was formatted/syntaxed incorrectly. (It looked like python code, not yaml syntax). For some reason I never decided to look at the .yaml files. I'm terribly sorry for any time wasted.

**Comment by gillescastel** [comment]
No need to feel embarrassed. Glad your issue is fixed!

We should probably throw an error when yaml parsing fails.
