### ISSUE TITLE
Local Error

### ISSUE THREAD

**Issue by f82maroa** [gillescastel/university-setup#7]
Hi!, I'm studying physics in Spain and I want to import this workflow to my student life. I don't know what to do with the scripts. When i execute one of this, for example, course.py, I get this error:

`Traceback (most recent call last):
  File "courses.py", line 5, in <module>
    from lectures import Lectures
  File "/home/alvaro/university-setup/scripts/lectures.py", line 14, in <module>
    locale.setlocale(locale.LC_TIME, "nl_BE.utf8")
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
`
I only clone this repository to my user's directory and created the files that you comment in the blog. I have to do something more?

**Comment by SalmonA** [comment]
You can check for locales available on your system with `locale -a`. Replace `nl_BE.utf8` in lectures.py with something on that list that makes sense for your location, maybe something like `es_ES.utf8`

**Comment by f82maroa** [comment]
> You can check for locales available on your system with `locale -a`. Replace `nl_BE.utf8` in lectures.py with something on that list that makes sense for your location, maybe something like `es_ES.utf8`

It was that, thank you :) 
But I don't know why rofi has the same error... I decided to do an script similiar in bash using the linked files due to this issue and works

**Comment by gillescastel** [comment]
Good question @f82maroa, and thanks @SalmonA for answering! Closing this.
